services:
  meilisearch:
    image: getmeili/meilisearch:v1.12
    container_name: meilisearch
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=MASTER_KEY
    volumes:
      - ./meili_data:/meili_data
    restart: unless-stopped

  nuxt:
    build:
      context: .
      dockerfile: nuxt.dockerfile
    container_name: nuxt
    ports:
      - "3000:3000"
    restart: unless-stopped

  # solr:
  #   image: solr:9.7.0
  #   ports:
  #     - "8983:8983"
  #   volumes:
  #     - ./solr_data:/var/solr
  #   command:
  #     - solr-precreate
  #     - gettingstarted
  #   restart: unless-stopped
